// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVsrCJg8qGlXvulnzqE1GagmUDy5VN2f4',
    appId: '1:54380035317:android:b88d04512fc7a9025f59bc',
    messagingSenderId: '54380035317',
    projectId: 'd-generator-a541a',
    databaseURL: 'https://d-generator-a541a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'd-generator-a541a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkoGZheswl17zSuhQwyyIaF_uuFTHP3Is',
    appId: '1:54380035317:ios:126af988c4b9b2b55f59bc',
    messagingSenderId: '54380035317',
    projectId: 'd-generator-a541a',
    databaseURL: 'https://d-generator-a541a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'd-generator-a541a.appspot.com',
    iosClientId: '54380035317-e1irkq3dlfn99077fh38p9n8ctubph9b.apps.googleusercontent.com',
    iosBundleId: 'com.luckygenerator.luckyGenerator',
  );
}
